# These are supported funding model platforms
custom:
  - https://etherscan.io/address/0xa977ED7922703Bf4F9A14cFd27c56d3Cc571908C
  - https://solscan.io/account/3TcijsNw7kL97QmaLHNE8gDeKt177w4PsJd8XMWDQjUn